### ISSUE TITLE
Unable to assemble ship with INDEV-H

### ISSUE THREAD

**Issue by DanTheColoradan** [elytra/archimedes-ships-plus#84] opened 2016-05-07 18:59 UTC
I attempted to create a flying ship. I tried several different blocks including just balloons, planks, and stone. It won't move past "Assembling...".

![screen shot 2016-05-07 at 12 55 52 pm](https://cloud.githubusercontent.com/assets/3826143/15093938/0ee3339a-1453-11e6-9065-17aaf34e643f.png)

There aren't any errors in the server logs.

MC: 1.8.9
Server Forge: 11.15.1.1764
archimedesshipsplus-MC1.8.9-INDEV-H.jar
movingworld-MC1.8.9-INDEV-H-full.jar *and* INDEV-I-full.jar

**Comment by Aetheros** [comment] 2016-05-08 16:55
I can confirm this error persisting up until Forge Version 11.15.1.1890

**Comment by darkevilmac** [comment] 2016-05-08 16:59
Please attach your latest-log file after running the game with this issue.
Moving world and Archimedes ships don't often print directly to the console.

**Comment by Aetheros** [comment] 2016-05-08 17:44
https://gist.github.com/Aetheros/515b1c9ba37dbc2c0424c61a2a310da8

I've attached it in this gist.

It just recieves the event and nothing happens.

**Comment by Holgath** [comment] 2016-05-11 04:12
I also have this problem on my main server.  I have a test server that I run on my personal computer and it works just fine on that, but when I upload it to my hosted server I can't get past the assembling stage.  It is weird because my settings are pretty much they same on both.  Is there maybe a minimum java version that needs to be used?

This is the version on the server that doesn't work.  It is the line taken from the console in forge.  I have also included the information from the server that doesn't work.  

Server that doesn't work
Forge version 11.15.1.1890

Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_66, running on Linux:amd64:3.10.23-xxxx-std-ipv6-64

Server that does work
Forge Version 11.15.1.1890

Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_73, running on Windows 7:amd64:6.1

**Comment by Holgath** [comment] 2016-05-11 04:14
I figured out that on my main server since it uses linux it has the following option defaulted to True in server.properties.  If you set it to False it will allow the ship to assemble.  

use-native-transport

**Comment by Aetheros** [comment] 2016-05-11 13:20
Okay, so going by that option, the error will be in the packet exchange system. You might want to review that code @darkevilmac

**Comment by darkevilmac** [comment] 2016-05-12 04:30
See #86

**Closed by darkevilmac** 2016-05-12 04:30 UTC
